/* Original score metadata; generated by tools/compose-soundtrack-v170.py. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ShuMusicTracks=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){return {
  "map-spring": {
    "title": "春・花びらの小径",
    "src": "assets/audio/music-v170/map-spring.mp3",
    "duration": 48.0,
    "bpm": 80
  },
  "map-summer": {
    "title": "夏・青葉と川風",
    "src": "assets/audio/music-v170/map-summer.mp3",
    "duration": 40.0,
    "bpm": 96
  },
  "map-autumn": {
    "title": "秋・茜の水面",
    "src": "assets/audio/music-v170/map-autumn.mp3",
    "duration": 56.470588235294116,
    "bpm": 68
  },
  "map-winter": {
    "title": "冬・雪待ち灯り",
    "src": "assets/audio/music-v170/map-winter.mp3",
    "duration": 64.0,
    "bpm": 60
  },
  "home": {
    "title": "ただいま、相棒",
    "src": "assets/audio/music-v170/home.mp3",
    "duration": 53.333333333333336,
    "bpm": 72
  },
  "sam": {
    "title": "サムの釣具日和",
    "src": "assets/audio/music-v170/sam.mp3",
    "duration": 41.73913043478261,
    "bpm": 92
  },
  "shrine": {
    "title": "星を結ぶ祈り",
    "src": "assets/audio/music-v170/shrine.mp3",
    "duration": 68.57142857142857,
    "bpm": 56
  },
  "inn": {
    "title": "水守りの宵布団",
    "src": "assets/audio/music-v170/inn.mp3",
    "duration": 60.0,
    "bpm": 64
  },
  "yaoya": {
    "title": "朝採れの籠",
    "src": "assets/audio/music-v170/yaoya.mp3",
    "duration": 38.4,
    "bpm": 100
  },
  "diner": {
    "title": "湯気の向こうで",
    "src": "assets/audio/music-v170/diner.mp3",
    "duration": 45.714285714285715,
    "bpm": 84
  },
  "fish-market": {
    "title": "朝市の銀うろこ",
    "src": "assets/audio/music-v170/fish-market.mp3",
    "duration": 36.92307692307692,
    "bpm": 104
  },
  "boats": {
    "title": "港の舟支度",
    "src": "assets/audio/music-v170/boats.mp3",
    "duration": 43.63636363636363,
    "bpm": 88
  }
};});
